name: CI
on: { pull_request: { } }
concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
            distribution: temurin
            java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build app
        run:
          ./gradlew build

      - name: Upload apk
        uses: actions/upload-artifact@v4
        with:
            name: gps-clock.apk
            path: ./app/build/outputs/apk/*/*.apk
            retention-days: 7
